== GraphQL + Ratpack

"Ratpack is a set of Java libraries for building scalable HTTP
applications.  It is a lean and powerful foundation, not an
all-encompassing framework."
-- www.ratpack.io

=== Create project

To create a Ratpack project is pretty straight forward thanks to
http://www.sdkman.io[SDKMan] and
https://github.com/pledbrook/lazybones[Lazybones]. First install
**sdkman** following the instructions found in its site. Then add the
following property to your `$HOME/.lazybones/config.groovy` (create
the file if it doesn't exists yet)

[source, groovy]
.config.groovy
----
bintrayRepositories = [
  "ratpack/lazybones"
]
----

That will make available the Ratpack latest templates to create a
Ratpack project. Once this property has been set then you can start
using Lazybones to create your first project.

[source, shell]
.shell
----
lazybones create ratpack 1.5.1 fortune-cookies-ratpack
----

This will create a new project called `ratpack-graphql-sample` with
the following structure (copied from Lazybones execution).

[source, text, indent=0]
----
    <proj>
      |
      +- src
          |
          +- ratpack
          |     |
          |     +- Ratpack.groovy
          |     +- ratpack.properties
          |     +- public // Static assets in here
          |          |
          |          +- images
          |          +- lib
          |          +- scripts
          |          +- styles
          |
          +- main
          |   |
          |   +- groovy
                   |
                   +- // App classes in here!
          |
          +- test
              |
              +- groovy
                   |
                   +- // Spock tests in here!
----


=== GraphQL handler

Now that we have the basic structure of a Ratpack project, lets make
available a GraphQL handler that will expose the execution engine in a
specific HTTP endpoint.

[source, groovy]
.build.gradle
----
include::{ratpack}/build.gradle[tags=gql-ratpack, indent=0]
----

[source, groovy]
.Ratpack.groovy
----
include::{ratpack}/src/ratpack/Ratpack.groovy[indent=0]
----


=== GraphiQL handler



=== Schema

Instead of coding the schema with Groovy we're going to use GraphQL
syntax directly modularising the schema. Modularising the way you
create GraphQL schemas has at least a couple of benefits:

Enables you to write using plain GraphQL language: Writing code is
cool, but you may be used to writing GraphQL schemas using the GraphQL
language directly.

It allows you to separate parts of the schema by areas of interest: No
more a huge single file declaring everything in one place

=== Handling errors

NOTE: You can check how `graphql-java` handles exception during query
execution at http://graphql-java.readthedocs.io/en/v7/execution.html

=== Security

(TODO)

==== Authentication

(TODO)

==== Authorization

(TODO)